# FSC Global Configuration

# FSC 核心配置
fsc:
  debug: true
  version: "2.0"

# Baidu 地图 API
baiduMap:
  api: "http://api.map.baidu.com"
  accessKey: "zqZrWc3iKoMsMRmUjrQyzneeWhIPxGvV"
  secretKey: "tvomES1GLg7w8N3rp2aoCXSoPHrQ28l0"


# 高效体育接口与加密 key（不了解请勿修改）
sportCampus:
  api: "https://www.sportcampus.cn"
  encryptionKey: "lpKK*TJE8WaIg%93O0pfn0#xS0i3xE$z"

# 高校体育登录账号
account:
  mobile: "" # 登录账号
  password: "" # 密码
  phoneType: "" #手机类型，iPhone X，iPhone 7 等
  uuid: "" # 唯一特征码，如果你知道自己之前的特征码，就尽量填写之前的（防风控），如果不知道，就留空，FSC 会自动生成。

# 面板
panel:
  redDot: 1 # 跑几个红点
  greenDot: 2 # 跑几个绿点

# logger configuration
log:
    prefix: '[FSC]'
    log-file: false
    stdout: 'DEBUG'
    file: 'DEBUG'